QDeclarativeTextToSpeech: fix GCC13 -Wuse-after-free
I don't see what the original code did wrong, but GCC13 doesn't
understand it, and spews out the following:

In copy constructor ‘Qt6::QtPrivate::QExplicitlySharedDataPointerV2<T>::QExplicitlySharedDataPointerV2(const Qt6::QtPrivate::QExplicitlySharedDataPointerV2<T>&) [with T = Qt6::QMapData<std::map<Qt6::QString, Qt6::QVariant, std::less<Qt6::QString>, std::allocator<std::pair<const Qt6::QString, Qt6::QVariant> > > >]’,
    inlined from ‘Qt6::QMap<Qt6::QString, Qt6::QVariant>::QMap(const Qt6::QMap<Qt6::QString, Qt6::QVariant>&)’ at qmap.h:185:7,
    inlined from ‘Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>::<lambda>(const Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>&)’ at qdeclarativetexttospeech.cpp:106:30,
    inlined from ‘constexpr __gnu_cxx::__ops::_Iter_pred<Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)> >::_Iter_pred(const __gnu_cxx::__ops::_Iter_pred<Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)> >&)’ at /d/gcc/13/include/c++/13.0.1/bits/predefined_ops.h:304:12,
    inlined from ‘constexpr _Iterator std::__find_if(_Iterator, _Iterator, _Predicate) [with _Iterator = Qt6::QList<Qt6::QVoice>::const_iterator; _Predicate = __gnu_cxx::__ops::_Iter_pred<Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)> >]’ at /d/gcc/13/include/c++/13.0.1/bits/stl_algobase.h:2115:23,
    inlined from ‘constexpr _IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = Qt6::QList<Qt6::QVoice>::const_iterator; _Predicate = Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>]’ at /d/gcc/13/include/c++/13.0.1/bits/stl_algo.h:3923:28,
    inlined from ‘auto Qt6::QtPrivate::sequential_erase_if(Container&, Predicate&) [with Container = Qt6::QList<Qt6::QVoice>; Predicate = Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>]’ at qcontainertools_impl.h:333:35,
    inlined from ‘Qt6::qsizetype Qt6::QList<T>::removeIf(Predicate) [with Predicate = Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>; T = Qt6::QVoice]’ at qlist.h:589:46,
    inlined from ‘Qt6::QList<Qt6::QVoice> Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const’ at qdeclarativetexttospeech.cpp:106:20:
qshareddata_impl.h:40:11: error: pointer used after ‘void operator delete(void*, std::size_t)’ [-Werror=use-after-free]
   40 |         : d(other.d)
      |           ^~~~~~~~~~
In destructor ‘Qt6::QtPrivate::QExplicitlySharedDataPointerV2<T>::~QExplicitlySharedDataPointerV2() [with T = Qt6::QMapData<std::map<Qt6::QString, Qt6::QVariant, std::less<Qt6::QString>, std::allocator<std::pair<const Qt6::QString, Qt6::QVariant> > > >]’,
    inlined from ‘Qt6::QtPrivate::QExplicitlySharedDataPointerV2<T>::~QExplicitlySharedDataPointerV2() [with T = Qt6::QMapData<std::map<Qt6::QString, Qt6::QVariant, std::less<Qt6::QString>, std::allocator<std::pair<const Qt6::QString, Qt6::QVariant> > > >]’ at qshareddata_impl.h:65:5,
    inlined from ‘Qt6::QMap<Qt6::QString, Qt6::QVariant>::~QMap()’ at qmap.h:185:7,
    inlined from ‘Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>::~<lambda>()’ at qdeclarativetexttospeech.cpp:106:30,
    inlined from ‘constexpr __gnu_cxx::__ops::_Iter_pred<_Predicate> __gnu_cxx::__ops::__pred_iter(_Predicate) [with _Predicate = Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>]’ at /d/gcc/13/include/c++/13.0.1/bits/predefined_ops.h:325:58,
    inlined from ‘constexpr _IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = Qt6::QList<Qt6::QVoice>::const_iterator; _Predicate = Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>]’ at /d/gcc/13/include/c++/13.0.1/bits/stl_algo.h:3923:28,
    inlined from ‘auto Qt6::QtPrivate::sequential_erase_if(Container&, Predicate&) [with Container = Qt6::QList<Qt6::QVoice>; Predicate = Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>]’ at qcontainertools_impl.h:333:35,
    inlined from ‘Qt6::qsizetype Qt6::QList<T>::removeIf(Predicate) [with Predicate = Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const::<lambda(const Qt6::QVoice&)>; T = Qt6::QVoice]’ at qlist.h:589:46,
    inlined from ‘Qt6::QList<Qt6::QVoice> Qt6::QDeclarativeTextToSpeech::findVoices(const Qt6::QVariantMap&) const’ at qdeclarativetexttospeech.cpp:106:20:
qshareddata_impl.h:68:13: note: call to ‘void operator delete(void*, std::size_t)’ here
   68 |             delete d;
      |             ^~~~~~~~

Fix by taking the QVariantMap by reference instead of by value. That
should be a bit more efficient, too, due to reduced atomic ref count
manipulations.

Amends 3543b7c3b69d69280122958f5949ac7827c543b0.

Change-Id: I3070ba17544ca71c9ab835cd6f6fd2e2748ef74a
Reviewed-by: Jarkko Koivikko <jarkko.koivikko@code-q.fi>
Reviewed-by: Jeremy Whiting <jpwhiting@kde.org>
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit 3ed098e7c87f1036bc195c26c9aaf5fa3e417a93)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>